/*
 * File: app/view/SpelledViewport.js
 * Date: Wed Mar 21 2012 15:30:51 GMT+0100 (W. Europe Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Spelled.view.SpelledViewport', {
    extend: 'Spelled.view.ui.SpelledViewport',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});