/*
 * File: app/view/ui/SpelledViewport.js
 * Date: Tue Apr 10 2012 14:17:40 GMT+0200 (W. Europe Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spelled.view.ui.SpelledViewport', {
    extend: 'Ext.container.Viewport',


    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 1000,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            flex: 1,
                            items: [
//                                {
//                                    xtype: 'treepanel',
//                                    height: 279,
//                                    width: 592,
//                                    title: 'Zones',
//                                    store: [{"my_variable1":"value1","my_variable2":"value2"},{"id":"node1","text":"Node 1"}],
//                                    viewConfig: {
//
//                                    }
//                                },
//                                {
//                                    xtype: 'treepanel',
//                                    height: 634,
//                                    width: 592,
//                                    title: 'Assets & Entities',
//                                    store: [{"my_variable1":"value1","my_variable2":"value2"},{"id":"node1","text":"Node 1"}],
//                                    flex: 1,
//                                    viewConfig: {
//
//                                    }
//                                },
                                {
                                    xtype: 'propertygrid',
                                    height: 250,
                                    title: 'Configuration',
                                    source: {
                                        'Property 1': 'String',
                                        'Property 2': true,
                                        'Property 3': '2012-04-10T11:52:41',
                                        'Property 4': 123
                                    },
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            activeTab: 1,
                            flex: 1,
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 521,
                                    width: 804,
                                    title: 'Rendered Zone'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Script'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Image'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});