#!/bin/sh

ACTION=$1

if [ -z $ACTION ]; then
	echo Usage: $0 action
	echo
	echo Available actions:
	echo
	echo theme - recompile the theme from sass files
	echo build - compile a new deployable version of the app
	echo
	exit
fi

CWD=$(pwd)
SENCHA=$CWD/../SenchaCmd/sencha

if [ "$ACTION" = "theme" ]; then
	cd public/packages/spelled-theme
	$SENCHA package build
	cd $CWD

elif [ "$ACTION" = "build" ]; then
	# cleaning up and creating directory tree
        rm -rf build
        mkdir build

        cd public
        $SENCHA app build
        cd $CWD
        
	# copy sencha build
	cp public/build/spellEd/production/index.html build/
	cp public/build/spellEd/production/all-classes.js build/
	cp -R public/build/spellEd/production/resources build/

	# populating output with static content
        cp -RL public/libs build
        cp ../../node_modules/requirejs/require.js build/libs
        cp ../../node_modules/underscore/underscore.js build/libs
        cp -R ../ace/lib/ace build/libs
fi
