#!/bin/sh

ACTION=$1

if [ -z $ACTION ]; then
	echo Usage: $0 action
	echo
	echo Available actions:
	echo bootstrap - create new bootstrap file
	exit
fi

UNAME=$(uname -sm)

if [ "$UNAME" = "Linux i386" ]; then
	PLATFORM="linux-ia32"

elif [ "$UNAME" = "Linux x86_64" ]; then
	PLATFORM="linux-x64"

elif [ "$UNAME" = "Darwin i386" ]; then
	PLATFORM="osx-ia32"

elif [ "$UNAME" = "Darwin x86_64" ]; then
	PLATFORM="osx-ia32"
fi

if [ -z $PLATFORM ]; then

	echo Your platform \"$UNAME\" is not supported.
	exit
fi

SENCHA=../SenchaCmd/$PLATFORM/sencha

if [ "$ACTION" = "bootstrap" ]; then
	$SENCHA compile -classpath=../extjs/src,public/app meta -alias -out public/bootstrap.js and meta -alt -append -out public/bootstrap.js
fi




