#!/bin/sh

PACKAGE_NAME=nw-package
PUBLIC_FOLDER=$PACKAGE_NAME/public

echo "Deleting old package"
rm -rf $PACKAGE_NAME

echo "Start build process"
make deploy

echo "Create new package folder"
mkdir $PACKAGE_NAME
mkdir $PUBLIC_FOLDER

echo "Copy files to package"
cp -aR build/* $PUBLIC_FOLDER

cp package.json $PACKAGE_NAME/.
cp -aR src $PACKAGE_NAME

#cp server $PACKAGE_NAME/.
echo "Copy node modules files to package"
cp -aR ../../node_modules $PACKAGE_NAME


#zip -r nw-package.zip public src server ../../node_modules


