#!/bin/sh

CUR_DIR=$(pwd)
PACKAGE_NAME=nw-package
PUBLIC_FOLDER=$PACKAGE_NAME/public
NODE_WEB_KIT_FOLDER=nodeWebKit
SPELL_CORE_FOLDER=../spellCore
SPELL_CORE_TARGET_FOLDER=$PACKAGE_NAME/spellCore

echo "Deleting old package"
rm -rf $PACKAGE_NAME

echo "Start spellEd build process"
make deploy

echo "Building SpellCore..."
cd $SPELL_CORE_FOLDER
make deploy
cd $CUR_DIR

echo "Create new package folder"
mkdir $PACKAGE_NAME
mkdir $PUBLIC_FOLDER
mkdir $SPELL_CORE_TARGET_FOLDER
mkdir $SPELL_CORE_TARGET_FOLDER/build

echo "Copy spellEd files to package"
cp -aR build/* $PUBLIC_FOLDER

echo "Copy spellCore files to package"
cp -aR $SPELL_CORE_FOLDER/publicTemplate $SPELL_CORE_FOLDER/library $SPELL_CORE_TARGET_FOLDER
cp $SPELL_CORE_FOLDER/build/spell.util.js $SPELL_CORE_TARGET_FOLDER/build/.
cp $SPELL_CORE_FOLDER/build/spell.deploy.js $SPELL_CORE_TARGET_FOLDER/build/.
cp $SPELL_CORE_FOLDER/build/spell.loader.js $SPELL_CORE_TARGET_FOLDER/build/.

cp -aR $NODE_WEB_KIT_FOLDER/* $PACKAGE_NAME/.
cp -aR src $PACKAGE_NAME

echo "Copy node modules files to package"
cp -aR ../../node_modules $PACKAGE_NAME


#zip -r nw-package.zip public src server ../../node_modules


