#!/usr/bin/env node

var requirejs = require( 'requirejs' ),
	fs        = require( 'fs' ),
	path      = require( 'path' ),
	spellPath = path.resolve( process.mainModule.filename , '..' ),
	define    = requirejs.define

requirejs.config( {
	baseUrl: spellPath + '/src',
	nodeRequire: require
} )

//load needed spell util scripts
eval( fs.readFileSync( path.resolve( spellPath, '../spellCore/build/spell.util.js' ), 'utf8' ) )

requirejs(
	[
		'server/spellEdServer'
	],
	function(
		spellEdServer
	) {
		spellEdServer( process.argv, process.cwd(), spellPath )
	}
)
