#!/usr/bin/env node

var requirejs = require( 'requirejs' ),
	fs        = require( 'fs' ),
	path      = require( 'path' ),
	spellPath = path.resolve( process.mainModule.filename, '..' ),
	define    = requirejs.define

requirejs.config( {
	baseUrl: spellPath + '/src',
	paths: {
		'spell-shared': spellPath + '/node_modules/spell-shared'
	},
	nodeRequire: require
} )

requirejs(
	[
		'server/spellEdServer'
	],
	function(
		spellEdServer
	) {
		spellEdServer( process.argv, process.cwd(), spellPath )
	}
)
