#!/bin/sh

cp elbow-minus.gif elbow-end-minus.gif
cp elbow-minus.gif elbow-end-minus-nl.gif
cp elbow-minus.gif elbow-minus-nl.gif


cp elbow-plus.gif elbow-end-plus.gif
cp elbow-plus.gif elbow-end-plus-nl.gif
cp elbow-plus.gif elbow-plus-nl.gif

